const STATUS_CODES = {
    SUCCESS : 200,
    CREATED : 201,
    UNAUTHORIZED : 401,
    FORBIDDEN : 403,
    SERVER_ERROR : 500,
    NOT_FOUND : 404,
    BAD_REQUEST : 400,
    
}

module.exports = {STATUS_CODES}